[2024-09-09T11:21:18.638] [ERROR] error - Error: [2] Token Unauthorized
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:27:19
    at Generator.next (<anonymous>)
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:4:12)
    at auth (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:14:26)
    at Layer.handle [as handle_request] (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\layer.js:95:5) {
  code: 401,
  status: 'error'
}
[2024-09-09T11:58:15.677] [ERROR] error - Error: [2] Token Unauthorized
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:27:19
    at Generator.next (<anonymous>)
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:4:12)
    at auth (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:14:26)
    at Layer.handle [as handle_request] (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\layer.js:95:5) {
  code: 401,
  status: 'error'
}
[2024-09-11T10:46:12.507] [ERROR] error - testing error CheckTOken Error: Internal server error.
[2024-09-11T10:46:12.508] [ERROR] error - Error: Internal server error.
    at D:\Dev SIPPP\PMO\usman\src\services\api\v1\aksesSippp-api.ts:870:15
    at Generator.throw (<anonymous>)
    at rejected (D:\Dev SIPPP\PMO\usman\src\services\api\v1\aksesSippp-api.ts:29:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 500,
  status: 'error'
}
[2024-09-11T13:41:44.969] [ERROR] error - Error: [2] Token Unauthorized
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:27:19
    at Generator.next (<anonymous>)
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:4:12)
    at auth (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:14:26)
    at Layer.handle [as handle_request] (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:328:13)
    at D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:346:12) {
  code: 401,
  status: 'error'
}
